<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerITh79lp\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerITh79lp/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerITh79lp.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerITh79lp\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerITh79lp\App_KernelProdDebugContainer([
    'container.build_hash' => 'ITh79lp',
    'container.build_id' => 'adb76d9c',
    'container.build_time' => 1729727400,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerITh79lp');
