<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIlzXu5k\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIlzXu5k/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerIlzXu5k.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerIlzXu5k\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerIlzXu5k\App_KernelProdContainer([
    'container.build_hash' => 'IlzXu5k',
    'container.build_id' => 'c1f2bb8a',
    'container.build_time' => 1729855853,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIlzXu5k');
