<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_ActionDefinitionEdit' => [[], ['_controller' => 'App\\Controller\\ActionDefinitionEditController::index'], [], [['text', '/action/definition/edit']], [], [], []],
    'app_ActionEdit' => [[], ['_controller' => 'App\\Controller\\ActionEditController::index'], [], [['text', '/action/edit']], [], [], []],
    'app_AdminEdit' => [[], ['_controller' => 'App\\Controller\\AdminEditController::editAdmin'], [], [['text', '/admin/edit']], [], [], []],
    'app_Home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'app_loginPage' => [[], ['_controller' => 'App\\Controller\\LoginController::loginPage'], [], [['text', '/login/page']], [], [], []],
    'app_logoutPage' => [[], ['_controller' => 'App\\Controller\\LoginController::logoutPage'], [], [['text', '/logout']], [], [], []],
    'app_PageRender' => [['page'], ['_controller' => 'App\\Controller\\PageController::index'], [], [['text', '.html'], ['variable', '/', '[^/\\.]++', 'page', true], ['text', '/pages']], [], [], []],
    'app_ReportPage' => [[], ['_controller' => 'App\\Controller\\ReportController::index'], [], [['text', '/report/selector']], [], [], []],
    'app_ReportDisplay' => [[], ['_controller' => 'App\\Controller\\ReportController::show'], [], [['text', '/report/show']], [], [], []],
    'app_TimeEdit' => [[], ['_controller' => 'App\\Controller\\TimeEditController::timeEdit'], [], [['text', '/time/edit']], [], [], []],
    'App\Controller\ActionDefinitionEditController::index' => [[], ['_controller' => 'App\\Controller\\ActionDefinitionEditController::index'], [], [['text', '/action/definition/edit']], [], [], []],
    'App\Controller\ActionEditController::index' => [[], ['_controller' => 'App\\Controller\\ActionEditController::index'], [], [['text', '/action/edit']], [], [], []],
    'App\Controller\AdminEditController::editAdmin' => [[], ['_controller' => 'App\\Controller\\AdminEditController::editAdmin'], [], [['text', '/admin/edit']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\LoginController::index' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'App\Controller\LoginController::loginPage' => [[], ['_controller' => 'App\\Controller\\LoginController::loginPage'], [], [['text', '/login/page']], [], [], []],
    'App\Controller\LoginController::logoutPage' => [[], ['_controller' => 'App\\Controller\\LoginController::logoutPage'], [], [['text', '/logout']], [], [], []],
    'App\Controller\PageController::index' => [['page'], ['_controller' => 'App\\Controller\\PageController::index'], [], [['text', '.html'], ['variable', '/', '[^/\\.]++', 'page', true], ['text', '/pages']], [], [], []],
    'App\Controller\ReportController::index' => [[], ['_controller' => 'App\\Controller\\ReportController::index'], [], [['text', '/report/selector']], [], [], []],
    'App\Controller\ReportController::show' => [[], ['_controller' => 'App\\Controller\\ReportController::show'], [], [['text', '/report/show']], [], [], []],
    'App\Controller\TimeEditController::timeEdit' => [[], ['_controller' => 'App\\Controller\\TimeEditController::timeEdit'], [], [['text', '/time/edit']], [], [], []],
];
