<?php

namespace App\Controller;

use App\Beans\Person;
use App\Exception\InvalidRequestException;
use App\Repository\PersonRepository;
use Psr\Log\LoggerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Traits\LoggerAwareTrait;
use App\Traits\DatabaseAwareTrait;
use App\Traits\MailerAwareTrait;
use Exception;

#[Route('/')]
class LoginController extends BaseController
{
    use LoggerAwareTrait;
    use DatabaseAwareTrait;
    use MailerAwareTrait;

    private $resetPwBody =    " <html><body> "
                            . " <b><i>This email was auto-generated by a request to reset your password.</b></i><br>"
                            . " <h4>DO NOT REPLY TO THIS EMAIL</h4><br>"
                            . " If you did not request this, please email tceva.trophyclub@gmail.com and ask that your account be locked.<br>"
                            . " <br>"
                            . " Your new password is <b>%password%</b> \n"
                            . " <br> "
                            . " Once you have logged on, you can change your password to something else by clicking "
                            . " on the 'EDIT' button under the Members tab.<br><br>"
                            . " TCEVA. "
                            . " </body></html>" ;

    #[Route('/login', name: 'app_login', methods: ['GET','POST'])]
    public function index(): Response
    {
       
        $this->setSessionParm('loggedInUser', null);  // Clearing session
        $people =  $this->queryService->getPersons(-1); // Fetch persons from the database
       
        // Handling actions
        $action= $this->request->get('action') ?  $this->request->get('action') :null;
        $enteredId= $this->request->get('userName') ?  $this->request->get('userName') :null;
        try{
            if ($action === null || !in_array($action, ['reset', 'login'])) {
                $this->addFlashMessage("error","Please login");
            } elseif ($action === "login") {
                $this->handleLogin($people, $enteredId);
                    return $this->render('home.html.twig', [
                ]);
            } elseif ($action === "reset") {
                $this->handleReset($people, $enteredId);
            }
        }
        catch(Exception $e){
            $this->addFlashMessage("error","Incorrect login");
            return $this->redirectToRoute("app_loginPage");
        }
        return $this->redirectToRoute("app_loginPage");

    }  
    #[Route('/login/page', name: 'app_loginPage', methods: ['GET'])]
    public function loginPage(): Response
    {
        return $this->render('login.html.twig', [
        ]);
    } 
    #[Route('/logout', name: 'app_logoutPage', methods: ['GET'])]
    public function logoutPage(): Response
    {
        $this->session->invalidate();
        return $this->render('home.html.twig', [
        ]);
    } 
    private function handleLogin($people, $enteredId) {
        $password = $this->getParm('password','')!= null ? trim($this->getParm('password')) : null;
        $valid = false;
        foreach ($people as $person) {
            if (in_array($person->getStatus(), ["M", "A", "G"])) {
              
                if ($enteredId === $person->getLogin()) {
                    $encpw = $person->getPassword();
                    $match = false;
                    // Password verification using bcrypt
                    if ($encpw !== null) {
                        $match = password_verify($password, $encpw);
                    }
                    if ($match) {
                        $this->setSessionParm('loggedInUser', $person);
                        $valid = true;
                    }
                    break;
                }
            }
        }

        if (!$valid) {
            throw new InvalidRequestException("Login failed");
        }
    }

    private function handleReset(array $people, $enteredId) {
        foreach ($people as $person) {
            if (in_array($person->getStatus(), ["M", "A", "G"])) {
                if ($enteredId === $person->getLogin()) {
                    $email = $person->getEmail();
                    if ($email !== null && strlen($email) > 0) {
                        $salt = password_hash(uniqid(), PASSWORD_BCRYPT);
                        //$newPw = $this->generateRandomPassword(10);
                        $newPw = $this->generateMemorablePassword(3,"-",true,false);
                        $enc = password_hash($newPw, PASSWORD_BCRYPT);
                        
                        // Update password in the database
                        $person->setPassword($enc);
                        $this->queryService->updatePersonAccess($person);

                        // Send reset email
                        $body = str_replace("%password%", $newPw, $this->resetPwBody);
                        $this->sendEmail($email, "TCEVA Account Password Reset", $body);
                    }
                }
            }
        }
    }
    function generateMemorablePassword($word_count = 3, $separator = '-', $add_numbers = true, $add_symbols = false) {
        // List of simple 3-letter words to use in the password
        $words = [
            "cat", "dog", "bat", "fox", "rat", "ant", "bee", "owl", "cow", "pig", "hen", "ram",
            "sun", "sky", "red", "box", "cup", "hat", "car", "bus", "jet", "pan", "key", "map",
            "net", "pin", "cap", "run", "tap", "top", "kit", "log", "fan", "mud", "bag", "pot",
            "jam", "nut", "web", "zip", "egg", "gum", "lip", "peg", "rod", "tin", "rug", "bin",
            "pop", "fit", "hop", "lip", "bug", "pad", "tag", "tip", "pen", "cub", "hip", "wig"
        ];
        
        // Shuffle the words array to ensure randomness
        shuffle($words);
    
        // Select the required number of words from the shuffled array
        $selected_words = array_slice($words, 0, $word_count);
    
        // Concatenate the words with the chosen separator
        $password = implode($separator, $selected_words);
    
        // Optionally add numbers to increase password complexity
        if ($add_numbers) {
            $password .= $separator . mt_rand(100, 999);
        }
    
        // Optionally add a random symbol
        if ($add_symbols) {
            $symbols = ['!', '@', '#', '$', '%', '^', '&', '*', '?'];
            $password .= $separator . $symbols[array_rand($symbols)];
        }
    
        return $password;
    }
    private function generateRandomPassword($length) {
        $characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $randomPassword = '';
        for ($i = 0; $i < $length; $i++) {
            $randomPassword .= $characters[rand(0, strlen($characters) - 1)];
        }
        return $randomPassword;
    }
}
