<?php

namespace ContainerIlzXu5k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionDefinitionEditControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ActionDefinitionEditController' shared autowired service.
     *
     * @return \App\Controller\ActionDefinitionEditController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ActionDefinitionEditController'] = $instance = new \App\Controller\ActionDefinitionEditController(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\ActionDefinitionEditController', $container));
        $instance->setLogger(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
        $instance->setEventDispatcher(($container->privates['App\\Services\\QueryService'] ?? $container->load('getQueryServiceService')));

        return $instance;
    }
}
