<?php

namespace ContainerIlzXu5k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ActionDefinitionEditController::index' => ['privates', '.service_locator.MXn_h_B.App\\Controller\\ActionDefinitionEditController::index()', 'getActionDefinitionEditControllerindexService', true],
            'App\\Controller\\ActionEditController::index' => ['privates', '.service_locator.MXn_h_B.App\\Controller\\ActionEditController::index()', 'getActionEditControllerindexService', true],
            'App\\Controller\\ReportController::show' => ['privates', '.service_locator.OcJdhL9.App\\Controller\\ReportController::show()', 'getReportControllershowService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ActionDefinitionEditController:index' => ['privates', '.service_locator.MXn_h_B.App\\Controller\\ActionDefinitionEditController::index()', 'getActionDefinitionEditControllerindexService', true],
            'App\\Controller\\ActionEditController:index' => ['privates', '.service_locator.MXn_h_B.App\\Controller\\ActionEditController::index()', 'getActionEditControllerindexService', true],
            'App\\Controller\\ReportController:show' => ['privates', '.service_locator.OcJdhL9.App\\Controller\\ReportController::show()', 'getReportControllershowService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ActionDefinitionEditController::index' => '?',
            'App\\Controller\\ActionEditController::index' => '?',
            'App\\Controller\\ReportController::show' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ActionDefinitionEditController:index' => '?',
            'App\\Controller\\ActionEditController:index' => '?',
            'App\\Controller\\ReportController:show' => '?',
        ]));
    }
}
