<?php

namespace ContainerIlzXu5k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportDatesService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Services\ReportDates' shared autowired service.
     *
     * @return \App\Services\ReportDates
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Services\\ReportDates'] = $instance = new \App\Services\ReportDates();

        $instance->setLogger(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        return $instance;
    }
}
