<?php

namespace Container40IUEJI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OcJdhL9.App\Controller\ReportController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OcJdhL9.App\\Controller\\ReportController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reportDates' => ['privates', 'App\\Services\\ReportDates', 'getReportDatesService', true],
        ], [
            'reportDates' => 'App\\Services\\ReportDates',
        ]))->withContext('App\\Controller\\ReportController::show()', $container);
    }
}
