<?php

namespace ContainerITh79lp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQueryServiceService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private 'App\Services\QueryService' shared autowired service.
     *
     * @return \App\Services\QueryService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Traits/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Services/QueryService.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ConnectionService.php';

        $a = new \App\Services\ConnectionService($container->getEnv('DB_NAME'), $container->getEnv('DB_USERNAME'), $container->getEnv('DB_PASSWRD'), $container->getEnv('DB_HOST_NAME'), $container->getEnv('DB_PORT'));

        $b = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        $a->setLogger($b);

        $container->privates['App\\Services\\QueryService'] = $instance = new \App\Services\QueryService($a);

        $instance->setLogger($b);

        return $instance;
    }
}
