<?php

namespace ContainerZxiHTP3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActionDefinitionEditControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MXn_h_B.App\Controller\ActionDefinitionEditController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MXn_h_B.App\\Controller\\ActionDefinitionEditController::index()'] = ($container->privates['.service_locator.MXn_h_B'] ?? $container->load('get_ServiceLocator_MXnHBService'))->withContext('App\\Controller\\ActionDefinitionEditController::index()', $container);
    }
}
