<?php

namespace ContainerZxiHTP3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarViewServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\CalendarViewService' shared autowired service.
     *
     * @return \App\Services\CalendarViewService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Traits/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Services/CalendarViewService.php';

        $container->privates['App\\Services\\CalendarViewService'] = $instance = new \App\Services\CalendarViewService();

        $instance->setLogger(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        return $instance;
    }
}
