<?php

namespace ContainerZxiHTP3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ReportController' shared autowired service.
     *
     * @return \App\Controller\ReportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Traits/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Traits/DatabaseAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ReportController.php';

        $container->services['App\\Controller\\ReportController'] = $instance = new \App\Controller\ReportController(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\ReportController', $container));
        $instance->setLogger(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
        $instance->setEventDispatcher(($container->privates['App\\Services\\QueryService'] ?? $container->load('getQueryServiceService')));

        return $instance;
    }
}
