<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxiHTP3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxiHTP3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZxiHTP3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZxiHTP3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZxiHTP3\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZxiHTP3',
    'container.build_id' => '464499b9',
    'container.build_time' => 1729640697,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxiHTP3');
