<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerERXROxF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerERXROxF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerERXROxF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerERXROxF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerERXROxF\App_KernelDevDebugContainer([
    'container.build_hash' => 'ERXROxF',
    'container.build_id' => '1a166194',
    'container.build_time' => 1729856195,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerERXROxF');
